sudo: required
dist: trusty
language: go
services:
- docker
go:
- master
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 119.23.243.149
jobs:
  include:
  - stage: build
    script:
    - go build .
    - docker build -t todolist .
    - docker images
  - stage: deploy
    script:
    - touch ~/.ssh/id_rsa
    - openssl aes-256-cbc -K $encrypted_a23839f05a66_key -iv $encrypted_a23839f05a66_iv
      -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no root@119.23.243.149 "~/update.sh $REGISTRY $REPOSITORY $MIRROR_NAME"